version: '0.2'
phases:
  pre_build:
    commands:
      - npm i -g npm
      - npm i
      - npm i -g aws-cdk
  build:
    commands:
      - npm run build
      - npx cdk deploy
artifacts:
  base-directory: cdk.out
  files: '**/*'
